export const initialDatabase = {
  D: {
    pictures: [
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "101",
        "DESCRIPTION PHOTO": "Le Tréport",
        "MOTS CLES": "Plage",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/D/100.JPG",
      },
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "102",
        "DESCRIPTION PHOTO": "Près d'Eu",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/101.jpg",
      },
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "104",
        "DESCRIPTION PHOTO": "Le Bourg d'Ault",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/D/102.jpg",
      },
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "105",
        "DESCRIPTION PHOTO": "Prise d'un aigle",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/D/103.jpg",
      },
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "108",
        "DESCRIPTION PHOTO": "Phare de Caieux",
        "MOTS CLES": "Plage",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/D/104.jpg",
      },
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "109",
        "DESCRIPTION PHOTO": "Caieux",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/105.jpg",
      },
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "110",
        "DESCRIPTION PHOTO": "Caieux",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/106.jpg",
      },
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "111",
        "DESCRIPTION PHOTO": "St Valery/Somme",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/107.jpg",
      },
      {
        CARNET: "E",
        DATE: "1874-1876",
        "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
        PHOTO: "112",
        "DESCRIPTION PHOTO": "Le Crotoy",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/108.jpg",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "100",
        "DESCRIPTION PHOTO": "Couverture",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/109.jpg",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "101",
        "DESCRIPTION PHOTO": "Sans titre",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/110.jpg",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "102",
        "DESCRIPTION PHOTO": "Sans titre",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/111.jpg",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "103",
        "DESCRIPTION PHOTO": "Corot",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/D/112.jpg",
      },
    ],
    name: "D",
    date: "unknown",
    technicalName: "D",
  },
  E: {
    pictures: [
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "104",
        "DESCRIPTION PHOTO": "Diaz",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/E/E2-100.JPG",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "105",
        "DESCRIPTION PHOTO": "Sans titre",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/E/E2-101.JPG",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "106",
        "DESCRIPTION PHOTO": "Ségé 1869",
        "MOTS CLES": "Copie",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/E/E2-102.JPG",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "107",
        "DESCRIPTION PHOTO": "Beaucé 1869",
        "MOTS CLES": "Copie",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/E/E2-104.JPG",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "108",
        "DESCRIPTION PHOTO": "Durand Brager 1869",
        "MOTS CLES": "Copie",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/E/E2-105.JPG",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "109",
        "DESCRIPTION PHOTO": "Brion 1869",
        "MOTS CLES": "Copie",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/E/E2-108.JPG",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "110",
        "DESCRIPTION PHOTO": "Mazure 1869",
        "MOTS CLES": "Copie",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/E/E2-109.JPG",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "111",
        "DESCRIPTION PHOTO": "Harpigures 1869",
        "MOTS CLES": "Copie",
        QUALITE: "*",
        cloudinaryPublicId: "giraud-images/E/E2-110.JPG",
      },
      {
        CARNET: "D",
        DATE: "1869-1870",
        "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
        PHOTO: "112",
        "DESCRIPTION PHOTO": "Sans titre 1869",
        "MOTS CLES": "Copie",
        QUALITE: " ",
        cloudinaryPublicId: "giraud-images/E/E2-111.JPG",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U101",
        "DESCRIPTION PHOTO": "Couverture",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/E/E2-112.JPG",
      },
    ],
    name: "E",
    date: "unknown",
    technicalName: "E",
  },
  U: {
    pictures: [
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U102",
        "DESCRIPTION PHOTO": "Carabiniers",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-101.JPG",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U103",
        "DESCRIPTION PHOTO": "Sans titre de Louis XIV a 1842",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-102.jpg",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U104",
        "DESCRIPTION PHOTO": "Grenadiers",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-103.jpg",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U105",
        "DESCRIPTION PHOTO": "Artillerie",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-104.jpg",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U106",
        "DESCRIPTION PHOTO": "Tambours",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-105.jpg",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U107",
        "DESCRIPTION PHOTO": "Dragons",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-106.jpg",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U108",
        "DESCRIPTION PHOTO": "Lanciers",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-107.jpg",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U109",
        "DESCRIPTION PHOTO": "Hussards",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-108.jpg",
      },
      {
        CARNET: "U",
        DATE: "NO DATE",
        "TITRE CARNET": "INFANTERIE MILITAIRE",
        PHOTO: "U110",
        "DESCRIPTION PHOTO": "Chasseurs a Cheval",
        "MOTS CLES": "Militaire",
        cloudinaryPublicId: "giraud-images/U/U16-109.jpg",
      },
      { cloudinaryPublicId: "giraud-images/U/U16-110.jpg" },
    ],
    name: "U",
    date: "unknown",
    technicalName: "U",
  },
};
