export const imagesData = [
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "100",
    "DESCRIPTION PHOTO": "Couverture",
    QUALITE: " ",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "101",
    "DESCRIPTION PHOTO": "Le Tréport",
    "MOTS CLES": "Plage",
    QUALITE: "*",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "102",
    "DESCRIPTION PHOTO": "Près d'Eu",
    QUALITE: " ",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "104",
    "DESCRIPTION PHOTO": "Le Bourg d'Ault",
    QUALITE: "*",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "105",
    "DESCRIPTION PHOTO": "Prise d'un aigle",
    QUALITE: "*",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "108",
    "DESCRIPTION PHOTO": "Phare de Caieux",
    "MOTS CLES": "Plage",
    QUALITE: "*",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "109",
    "DESCRIPTION PHOTO": "Caieux",
    QUALITE: " ",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "110",
    "DESCRIPTION PHOTO": "Caieux",
    QUALITE: " ",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "111",
    "DESCRIPTION PHOTO": "St Valery/Somme",
    QUALITE: " ",
  },
  {
    CARNET: "E",
    DATE: "1874-1876",
    "TITRE CARNET": "TREPORT BRETAGNE CONCARNEAU",
    PHOTO: "112",
    "DESCRIPTION PHOTO": "Le Crotoy",
    QUALITE: " ",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "100",
    "DESCRIPTION PHOTO": "Couverture",
    QUALITE: " ",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "101",
    "DESCRIPTION PHOTO": "Sans titre",
    QUALITE: " ",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "102",
    "DESCRIPTION PHOTO": "Sans titre",
    QUALITE: " ",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "103",
    "DESCRIPTION PHOTO": "Corot",
    QUALITE: " ",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "104",
    "DESCRIPTION PHOTO": "Diaz",
    QUALITE: " ",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "105",
    "DESCRIPTION PHOTO": "Sans titre",
    QUALITE: "*",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "106",
    "DESCRIPTION PHOTO": "Ségé 1869",
    "MOTS CLES": "Copie",
    QUALITE: " ",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "107",
    "DESCRIPTION PHOTO": "Beaucé 1869",
    "MOTS CLES": "Copie",
    QUALITE: "*",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "108",
    "DESCRIPTION PHOTO": "Durand Brager 1869",
    "MOTS CLES": "Copie",
    QUALITE: "*",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "109",
    "DESCRIPTION PHOTO": "Brion 1869",
    "MOTS CLES": "Copie",
    QUALITE: "*",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "110",
    "DESCRIPTION PHOTO": "Mazure 1869",
    "MOTS CLES": "Copie",
    QUALITE: "*",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "111",
    "DESCRIPTION PHOTO": "Harpigures 1869",
    "MOTS CLES": "Copie",
    QUALITE: "*",
  },
  {
    CARNET: "D",
    DATE: "1869-1870",
    "TITRE CARNET": "SALON-BEUZEVAL-LIEGE-DINARD",
    PHOTO: "112",
    "DESCRIPTION PHOTO": "Sans titre 1869",
    "MOTS CLES": "Copie",
    QUALITE: " ",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U101",
    "DESCRIPTION PHOTO": "Couverture",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U102",
    "DESCRIPTION PHOTO": "Carabiniers",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U103",
    "DESCRIPTION PHOTO": "Sans titre de Louis XIV a 1842",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U104",
    "DESCRIPTION PHOTO": "Grenadiers",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U105",
    "DESCRIPTION PHOTO": "Artillerie",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U106",
    "DESCRIPTION PHOTO": "Tambours",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U107",
    "DESCRIPTION PHOTO": "Dragons",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U108",
    "DESCRIPTION PHOTO": "Lanciers",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U109",
    "DESCRIPTION PHOTO": "Hussards",
    "MOTS CLES": "Militaire",
  },
  {
    CARNET: "U",
    DATE: "NO DATE",
    "TITRE CARNET": "INFANTERIE MILITAIRE",
    PHOTO: "U110",
    "DESCRIPTION PHOTO": "Chasseurs a Cheval",
    "MOTS CLES": "Militaire",
  },
];
